name: Backup Salesforce Metadata

on:
  # schedule:
    # Scheduled to run at midnight UTC every day
    # UNCOMMENT TO ENABLE
    # - cron: "15 5 * * 1-5"

  # Allows manual triggering from the GitHub Actions UI
  workflow_dispatch:

jobs:
  backup_metadata:
    runs-on: ubuntu-latest
    environment: production
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Use local action to perform Salesforce backup and create PR
      - name: Backup Salesforce Metadata
        uses: programmer-377/sf-retrieve@v1
        with:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
          # SOURCE_DIR: force-app/main/default/classes
          # BRANCH_NAME: main
          # FORCE_PUSH: false
          MANIFEST_DIR  : manifest/package.xml
          # SCRIPT_DIRECTORY: scripts/callApexSendEmailMethod.apex

      - name: Send Email
        shell: bash
        run: |
            sf org login sfdx-url --set-default --sfdx-url-file <(echo "${{ secrets.SFDX_AUTH_URL }}")
            sf apex run --file scripts/apex/callApexSendEmailMethod.apex
